common:
    lid_topic:  "/velodyne_points"
    imu_topic:  "/vectornav/IMU"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                  # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

preprocess:
    lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 125
    scan_rate: 10                # only need to be set for velodyne, unit: Hz,
    timestamp_unit: 3            # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 0.5

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    120
    det_range:     200.0
    extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic,

    # LiDAR to IMU from chunyang 这里指lidar在imu里的投影
    extrinsic_T: [ -0.095391, 0.152670, 0.055453]
    extrinsic_R: [0.999850,  0.017243,  0.001604,
                    0.017273, -0.999640, -0.020541,
                    0.001249,  0.020565, -0.999788]

    # IMU to LiDAR 投影
    # extrinsic_T: [ 0.09627, 0.15311, 0.05873]
    # extrinsic_R: [0.999850,  0.01727,  0.00124,
    #                 0.01724, -0.999630, 0.02056,
    #                 0.0016,  -0.02054, -0.999788]
                

publish:
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
